### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasGemmStridedBatchedExFix( handle, opa, opb, m, n, k, (void*)(&falpha), a, CUDA_R_16F, lda, stridea, b, CUDA_R_16F, ldb, strideb, (void*)(&fbeta), c, CUDA_R_16F, ldc, stridec, num_batches, CUDA_R_32F, CUBLAS_GEMM_DEFAULT_TENSOR_OP)`

### ISSUE THREAD

**Issue by zhouyaqian666** [yangyangyang127/PointCLIP_V2#26]
Thanks for your amazing work! I was trying to run zero-shot classification of modelnet40 using the pipeline you provided.However, there is an error.
`Traceback (most recent call last):
  File "main.py", line 128, in <module>
    main(args)
  File "main.py", line 95, in main
    trainer = build_trainer(cfg)
  File "/home/ubuntu/HDD/zyq/PointCLIP2/zeroshot_cls/Dassl3D/dassl/engine/build.py", line 11, in build_trainer
    return TRAINER_REGISTRY.get(cfg.TRAINER.NAME)(cfg)
  File "/home/ubuntu/HDD/zyq/PointCLIP2/zeroshot_cls/Dassl3D/dassl/engine/trainer.py", line 280, in __init__
    self.build_model()
  File "/home/ubuntu/HDD/zyq/PointCLIP2/zeroshot_cls/trainers/zeroshot.py", line 55, in build_model
    text_feat = textual_encoder()
  File "/home/ubuntu/anaconda3/envs/clipoint/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/HDD/zyq/PointCLIP2/zeroshot_cls/trainers/zeroshot.py", line 20, in forward
    text_feat = self.clip_model.encode_text(prompts).repeat(1, self.cfg.MODEL.PROJECT.NUM_VIEWS)
  File "/home/ubuntu/HDD/zyq/PointCLIP2/zeroshot_cls/clip/model.py", line 347, in encode_text
    x = self.transformer(x)
  File "/home/ubuntu/anaconda3/envs/clipoint/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/HDD/zyq/PointCLIP2/zeroshot_cls/clip/model.py", line 202, in forward
    return self.resblocks(x)
  File "/home/ubuntu/anaconda3/envs/clipoint/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/clipoint/lib/python3.7/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/home/ubuntu/anaconda3/envs/clipoint/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/HDD/zyq/PointCLIP2/zeroshot_cls/clip/model.py", line 186, in forward
    x = x + self.attention(self.ln_1(x))
  File "/home/ubuntu/HDD/zyq/PointCLIP2/zeroshot_cls/clip/model.py", line 183, in attention
    return self.attn(x, x, x, need_weights=False, attn_mask=self.attn_mask)[0]
  File "/home/ubuntu/anaconda3/envs/clipoint/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/clipoint/lib/python3.7/site-packages/torch/nn/modules/activation.py", line 1174, in forward
    attn_mask=attn_mask, average_attn_weights=average_attn_weights)
  File "/home/ubuntu/anaconda3/envs/clipoint/lib/python3.7/site-packages/torch/nn/functional.py", line 5158, in multi_head_attention_forward
    attn_output_weights = torch.baddbmm(attn_mask, q_scaled, k.transpose(-2, -1))
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasGemmStridedBatchedExFix( handle, opa, opb, m, n, k, (void*)(&falpha), a, CUDA_R_16F, lda, stridea, b, CUDA_R_16F, ldb, strideb, (void*)(&fbeta), c, CUDA_R_16F, ldc, stridec, num_batches, CUDA_R_32F, CUBLAS_GEMM_DEFAULT_TENSOR_OP)`
Looking forward to getting your reply!

**Comment by yangyangyang127** [comment]
Actually, I did not come across this error when I re-run this code. I think maybe the environment or data path has some problems?
